### ISSUE TITLE
Error in rendering

### ISSUE THREAD

**Issue by bguil** [kirianguiller/reactive-dep-tree#1]
On page https://surfacesyntacticud.github.io/guidelines/u/particular_phenomena/lvc/, a sentence is not well-displayed.

<img width="604" alt="conll_bug" src="https://user-images.githubusercontent.com/687155/113324080-fb52c000-9316-11eb-8bd7-e4f399a40722.png">

This seems to be links to an encoding in the conll code: line with token 5 contains "-" instead  of "_".

I do not correct the CoNLL file now, such that you can see the problem. Maybe the code of reactive-dep-tree should handle this kind of errors

**Comment by kirianguiller** [comment]
Thank you for opening the first issue Bruno :).
I just created [an issue](https://github.com/kirianguiller/conllup-js/issues/1) in the [conllup javascript library](https://github.com/kirianguiller/conllup-js) repo that handle the conll conversion to json object.

**Comment by kirianguiller** [comment]
It's fixed ! Thanks again :)
