### ISSUE TITLE
Bad display of multiword tokens

### ISSUE THREAD

**Issue by bguil** [kirianguiller/reactive-dep-tree#3]
The last example on [comp page](https://surfacesyntacticud.github.io/guidelines/u/relations/comp/) in SUD guidelines is not correctly displayed.

It seems that the CoNLL code is not well interpreted: with "Show conll", the multiword token "au" has the ID `8` instead of `8-9` in the original data.

**Comment by bguil** [comment]
This is a ping!

The same problem also appears on https://surfacesyntacticud.github.io/guidelines/u/relations/comp_cleft/ (second example).

**Comment by bguil** [comment]
The problem is still there: https://github.com/surfacesyntacticud/guidelines/issues/30…

**Comment by kirianguiller** [comment]
Hey Bruno, Thanks for the reminder, I'm checking this.

Just a note, it seems that the link you sent 2 days ago doesn't lead anywhere. There might be a problem in the redirection.

**Comment by kirianguiller** [comment]
Fixed with : https://github.com/surfacesyntacticud/guidelines/commit/2dc058a0c78f2cde30beefc2a21cfa54e1e18882

Thanks, I'm closing the issue :)
